[package]
name = "OdinWS"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
warp = { version = "0.4.2", features = ["websocket", "server"] }
